language: node_js
node_js:
  - 0.10
  - 0.11
env:
  - XUNIT_FILE=shippable/testresults/result.xml
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
before_install:
  - npm install -g istanbul
after_script:
  - ./node_modules/.bin/istanbul cover grunt -- -u tdd
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
